### ISSUE TITLE
Add an error token?

### ISSUE THREAD

**Issue by critiqjo** [Nemo157/hamlet#14]
It could be good to add a generic `Token::Error(E)` variant, so that parsers may convey that an error occurred.

``` rust
pub enum Token<'a, E> {
    ...
    Error(pub E),
}
```

I'll leave this open till someone gets time to think about the nitty-gritty details, and issue a PR...

**Comment by Nemo157** [comment]
The alternative is to just make sure that working with an `Iterator<Item=Result<Token, _>>` is nice. Something to look at once there's some good example code of what's currently painful about working with errors I think.

**Comment by critiqjo** [comment]
Yup, I too think that a fail-able parser should generate `Result<Token, E>`s.
