### ISSUE TITLE
Feature: CloserWriter

### ISSUE THREAD

**Issue by critiqjo** [Nemo157/hamlet#18]
Okay, the name is dumb! Anyway, here's the API I'd like:

``` rust
impl<E> CloserWriter<E> {
    pub fn from_io(w: &mut io::Write) -> CloserWriter<io::Error>;
    pub fn from_fmt(w: &mut fmt::Write) -> CloserWriter<fmt::Error>;

    // Returns the current depth (number of unclosed start_tags).
    // If an `EndTag` is given, verifies if it is correct.
    pub fn write(&mut self, token) -> Result<usize, CloserError<E>>;

    // closes the last tag and returns the new depth
    pub fn close_tag(&mut self) -> Result<usize, CloserError<E>>;

    // closes tags until the specified depth is reached
    pub fn close_till(&mut self, depth) -> Result<(), CloserError<E>>; // useful?
}

enum CloserError<E> {
    CloseUnmatched, // zero-depth close or invalid end-tag
    StreamError(E),
}
```

Maintaining a stack of tag names will do to accomplish this. Document that raw text, tag names or attribute names are not verified. May be we can provide another wrapper over this called `SafeWriter` in future. Another possible extension is pretty printing the tags.

**Comment by Nemo157** [comment]
Do you have an example of usage for this? I'm having difficulty thinking of how exactly to use it.

I also wonder if rather than being a writer it would be possible to do this as some sort of iterator adaptor, which would allow for more processing of the <s>events</s> tokens before writing if needed.

**Comment by critiqjo** [comment]
> I'm having difficulty thinking of how exactly to use it.

The only real use-case I thought of was to check whether every start tags have matching end tags. `write` is sufficient to do that. `close_tag` and `close_until` are just fancy add-ons that came to my mind. Here's a forced use-case for `close_until`:

``` rust
let w = CloserWriter::from_io(..);
w.write(Token::start_tag("body", attrs!()));
w.write(Token::start_tag("ol", attrs!()));
w.write(Token::start_tag("li", attrs!()));
w.write(Token::text("hello"));
w.close_tag();
w.write(Token::start_tag("li", attrs!()));
w.write(Token::text("world"));
w.close_until(0);
//w.write(Token::end_tag("body")); // this should throw an error
```

> it would be possible to do this as some sort of iterator adaptor

I could imagine a `CloserWriter::write_iter<T>(&mut self, iter: T) -> Result<..>` method?

**Comment by Nemo157** [comment]
I just thought of the biggest potential problem with this:

``` rust
let w = CloserWriter::from_io(..);
w.write(Token::start_tag("body", attrs!()));
w.write(Token::start_tag("p", attrs!()));
w.write(Token::text("hello"));
w.write(Token::start_tag("br", attrs!()));
w.write(Token::text("world"));
w.close_until(0);
```

will result in the invalid html

``` html
<body><p>hello<br>world</br></p></body>
```

> Void elements only have a start tag; end tags must not be specified for void elements.
>  — [HTML5 §8.1.2](http://www.w3.org/TR/html/syntax.html#syntax-tags)

**Comment by critiqjo** [comment]
> I just thought of the biggest potential problem with this

:smile: Yup! I considered this too... If the number of void elements are less than 8, then it might as well check for those!

**Comment by critiqjo** [comment]
Just saw that there are 15!!

**Comment by Nemo157** [comment]
Yeah, it looks like foreign elements aren't allowed to be void, they either have to except content or be self closing. So checking for void elements should be doable :smile:.

**Comment by Nemo157** [comment]
Also, the way to do constructors that set some of the generic arguments is

``` rust
impl CloserWriter<io::Error> {
    pub fn from_io(w: &mut io::Write) -> CloserWriter<io::Error>;
}
impl CloserWriter<fmt::Error> {
    pub fn from_fmt(w: &mut fmt::Write) -> CloserWriter<fmt::Error>;
}
impl<E> CloserWriter<E> {
    pub fn write(&mut self, token) -> Result<usize, CloserError<E>>;
    ...
}
```

**Comment by critiqjo** [comment]
Ah I see... Is it then possible without specialization?

**Comment by Nemo157** [comment]
Yep, you're allowed multiple inherent `impl` blocks with different generic parameters as long as they don't define methods with the same name.

**Comment by Nemo157** [comment]
It's sort of like saying "when the error type is `X` then these methods are available".

**Comment by critiqjo** [comment]
Ah! Alright!! I somehow can't remember all the semantics...

**Comment by Nemo157** [comment]
Seems ok to me, I still can't think of any time I'd actually want to use it; I feel like I'd either be using high-level macros/builders that would generate the correct close tags or (when writing those high-level macros/builders) want to have complete control over what's being generated.

**Comment by critiqjo** [comment]
True enough! Now that I think about it, what I thought of doing was only for debugging. We might wanna verify the correctness of parsed/generated tokens. But once its correctness is proven (through enough tests), it's no longer a concern for a general user. So I guess we can close this...

**Comment by Nemo157** [comment]
That could be useful, maybe a separate crate `hamlet-validate` or similar. That would probably fit more as an iterator adaptor, maybe something like

``` rust
impl<I: Iterator<Item=Token>> Validator<I> {
    fn new(tokens: I) -> Validator<I>;
}
impl<I> Iterator for Validator<I> {
    type Item = Result<Token, ValidationError>;
    // ...
}
```

**Comment by critiqjo** [comment]
Yeah... And since it's named `Validator`, it might as well do a full-fledged validation of tag/attribute names (as well as raw text?)...

**Comment by critiqjo** [comment]
Also comments validation which should be easy...

But complete validation of tag/attribute names would mean checking them against a list! That's probably a _lot_ of work though! The simple syntactic validation (absence of symbols etc.) will be done during parsing anyway...

And raw text... I don't think that's doable!
