### ISSUE TITLE
Rename the repo?

### ISSUE THREAD

**Issue by critiqjo** [Nemo157/hamlet#3]
What I could come up with: html-duck, html-dodge, hornbill, hairtail, hamlet, ...

Suggest more and let's choose one...

**Comment by Nemo157** [comment]
:+1: I think avoiding a two part name would be best, if we split out the macros then a crate name like 'html-event-macros' is a bit unwieldy, and I can think of a few more tightly coupled crates that could follow a similar postfix naming scheme.

I don't have any suggestions right now, I'll try and brainstorm some later.

**Comment by critiqjo** [comment]
After some considerations, I vote for hamlet since it has all the characters of html and is the easiest to pronounce among the group (and the shortest one too)...
